---
driver:
  name: docker

platforms:
  - name: debian-6
    driver_config:
      image: chef/debian-6
      platform: debian
      require_chef_omnibus: false
  - name: debian-7
    driver_config:
      image: chef/debian-7
      platform: debian
      require_chef_omnibus: false
  - name: ubuntu-12.04
    driver_config:
      image: chef/ubuntu-12.04
      platform: ubuntu
      require_chef_omnibus: false
  - name: ubuntu-14.04
    driver_config:
      image: chef/ubuntu-14.04
      platform: ubuntu
      require_chef_omnibus: false
  - name: centos-6.4
    driver_config:
      image: chef/centos-6
      platform: centos
      require_chef_omnibus: false

suites:
  - name: docker
    run_list:
        - recipe[apt]
        - recipe[blackfire::mock]
        - recipe[blackfire]
    attributes:
        blackfire:
            agent:
                collector: 'http://127.0.0.1:8780'
                server_id: 'foo'
                server_token: 'bar'
                restart_mode: 'immediately'
